#!/usr/bin/env bash
# A Bash script that prints information about a domain and it's subdomain(s).
# This setup ensures the "printf" call is always made with the necessary arguments.

display_info ()
{
    domain="$1"
    subdomain="$2"

	# Use 'dig' to perform a DNS lookup and 'awk' to format the output
	dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"
}

for sbd in "www" "lb-01" "web-01" "web-02"
do
	 # If $2 is not provided or matches current subdomain...
	if [ -z "$2" ] || [ "$2" == "$sbd" ];
    then
		# ...call 'display_info' function with domain & current sbd.
		display_info "$1" "$sbd"
    fi
done
