#!/usr/bin/env bash
# A bash script that configures HAproxy as follows:
# 	- It send traffic to web-01 and web-02
#	- Distribute requests using a roundrobin algorithm

# Install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Make sure HAproxy can be managed via an init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Backup config file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Setup configuration
config="
frontend main
        bind *:80
	mode http
	default_backend web_servers
	
backend web_servers
	balance roundrobin
	server 283254-web-01 100.24.255.26 check
	server 283254-web-02 52.204.101.12 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Start HAProxy
sudo service haproxy restart
