#!/usr/bin/env bash
# A bash script that configures HAproxy as follows:
# 	- It send traffic to web-01 and web-02
#	- Distribute requests using a roundrobin algorithm

# Install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Make sure HAproxy can be managed via an init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Set ownership of HAproxy file to current user and ensure web roots permission
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

# Setup configuration
HCFG="\\\nfrontend main\n\tbind *:80\n\tdefault_backend web_servers\n\nbackend web_servers\n\tbalance roundrobin\n\tserver 283254-web-01 100.24.255.26 check\n\tserver 283254-web-02 52.204.101.12 check\n"
sudo sed -i "\$a $HCFG" /etc/haproxy/haproxy.cfg

# Start HAProxy
sudo service haproxy restart
