#!/usr/bin/env bash
# Install nginx and configure it to listen on port 80

# Update and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Remove the default configuration
sudo rm /etc/nginx/sites-enabled/default

# Create a symbolic link to enable the new default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart nginx
sudo service nginx restart