#!/usr/bin/env bash
# Bash (init) script 101-manage_my_process that manages manage_my_process.

arg=$1
case $arg in
	start)
		./manage_my_process &
		echo $! > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		read -r pid < /var/run/my_process.pid
		kill -9 "$pid"
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;
	restart)
		read -r pid < /var/run/my_process.pid
                kill -9 "$pid"
                rm /var/run/my_process.pid
		./manage_my_process &
                echo $! > /var/run/my_process.pid
                echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
