#!/usr/bin/env bash
# A Bash script that displays Best School 10 times, and 'Hi' on the 9th iteration.

counter=1
while [ $counter -le 10 ]
do
	echo "Best School"
	if [ $((counter)) == 9 ]; then
		echo "Hi"
	fi
	((counter++))
done
