#!/usr/bin/env bash
# A Bash script that loops from1 to 10 and displays 'bad luck' for the 4th loop iteration, 'good luck' for the 8th loop iteration and 'Best School' for the other iterations.

counter=1
while [ $counter -le 10 ]
do
	if [ $((counter)) == 4 ]; then
		echo "bad luck"
	elif [ $((counter)) == 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
