#!/usr/bin/env bash
# curl 0:8080: This is a request to a server at 'localhost' (0) on port 8080
# The apache server is already installed, but isn't running, which means
# 					it can't serve web pages yet.
# To fix it, simply start up the server.

sudo service apache2 start
