#!/usr/bin/env bash
# A Bash script that creates an RSA key pair.
# Name of created private = school
# Number of bits in key created = 4096
# Passphrase for created key = betty
ssh-keygen -f school -b 4096 -N 'betty'
